config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'staticpages#index'
  get 'team', to: 'staticpages#team'
  get '404' , to: "errors#not_found"
  get '422' , to: "errors#unacceptable"
  get '500' , to: "errors#internal_error"


  resources :charges

  devise_for :petsitters,  path: 'petsitters', controllers: { sessions: "petsitters/sessions", registrations: "petsitters/registrations", passwords: "petsitters/passwords"}
  devise_for :petowners, path: 'users', controllers: { sessions: "petowners/sessions", registrations: "petowners/registrations", passwords: "petowners/passwords"}
  resources :petsitters, only: [:show, :index] do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :petowners, only: [:show], path: 'profil' do
    resources :avatars, only: [:create]
  end

  resources :pets, only: [:new, :create] do
    resources :avatars, only: [:create]
  end
  resources :organizations, only: [:show, :index, :new, :create], :path => "associations"
  resources :petsittings, only: [:new, :create, :show, :update, :destroy]
  resources :contacts, only: [:new, :create]
  resources :comments, only: [:new, :create, :index]

end

app/models/petsitter.rb
class Petsitter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one_attached :avatar

  has_many :petdistricts
  has_many :districts, through: :petdistricts

  has_many :petsittings
  has_many :petowners, through: :petsittings

  after_create :account_validate_false
  # :demand_creation

  validates :first_name, presence: true, length: { minimum: 3 }
  validates :last_name, presence: true, length: { minimum: 3 }
  validates :describe, presence: true, length: { in: 20..1000 }
  validates :age, presence: true
  validates :phone_number, presence: true, format: { with: /\A(?:(?:\+|00)33[\s.-]{0,3}(?:\(0\)[\s.-]{0,3})?|0)[1-9](?:(?:[\s.-]?\d{2}){4}|\d{2}(?:[\s.-]?\d{3}){2})\z/, message: "Entrer un numero de telephone valide" }
  validates :living_space, presence: true

  def account_validate_false
  	@petsitter = Petsitter.last
  	@petsitter.account_validate = false
    @petsitter.avatar.attach(io: File.open('./app/assets/images/avatar_default/random_petsitter.jpg'), filename:"avatar.jpg")
	  @petsitter.save
  end

  def demand_creation
  	PetsitterMailer.demand_creation(self).deliver_now
  end

  # Petsitters selection via a district selected in index page
  def self.petsitters_district(params)
    @params_district = params
    @selected_district = Petdistrict.where(district_id: params)

    @petsitters_district = []
    @selected_district.each do |petsitter|
      if Petsitter.find_by(id: petsitter.petsitter_id).blank? == false
        @petsitters_district << Petsitter.find_by(id: petsitter.petsitter_id)
      end
    end
    return @petsitters_district
  end

# method for discriminate if account_validate is true, used mainly for AJAX in petsitters index
  def self.validate_petsitters(petsitter_district)
    @validate_petsitters = []

    @petsitters_district.each do |petsitter|
      if petsitter.account_validate == true
        @validate_petsitters << petsitter
      end
    end
    return @validate_petsitters
  end

end

app/controllers/petsitters/confirmations_controller.rb
# frozen_string_literal: true

class Petsitters::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/petsitters/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Petsitters::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/petsitters/passwords_controller.rb
# frozen_string_literal: true

class Petsitters::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/petsitters/registrations_controller.rb
# frozen_string_literal: true

class Petsitters::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.        
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :describe, :age, :phone_number, :garden, :living_space, :price, :district_ids])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
   devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :describe, :age, :phone_number, :garden, :living_space, :price, :district_ids])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/petsitters/sessions_controller.rb
# frozen_string_literal: true

class Petsitters::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/petsitters/unlocks_controller.rb
# frozen_string_literal: true

class Petsitters::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/petsitters_controller.rb
class PetsittersController < ApplicationController
  before_action :signed_in, only: [:show]

  def index
    @petsitters = Petsitter.all
    @districts = District.all_districts
    @params_district = params_district
    @selected_district = Petdistrict.where(district_id: params_district)

    # METHODE DANS MODEL PETSITTER
    if !params_district.nil?
      @petsitters_district = Petsitter.petsitters_district(params_district)

      @validate_petsitters = Petsitter.validate_petsitters(Petsitter.petsitters_district(params_district))
    end

    respond_to do |format|
      format.html { petsitters_path }
      format.js { }
    end


  end

  def show
    @petsitter = Petsitter.find(params[:id])
    #METHODE DANS LE MODEL COMMENTS
    @comments = Comment.all_comments_petsitter(params[:id])
    @district = District.find((Petdistrict.find_by(petsitter_id: params[:id])).district_id)



    if current_petsitter
      @bookings = Petsitting.where(petsitter_id: current_petsitter.id)
    end

    rescue ActiveRecord::RecordNotFound
      redirect_to root_url
      flash.now[:success] = "La page que vous avez demandé n'existe pas !"


  end

private

  def signed_in
    if current_petsitter.nil? & current_petowner.nil?
      redirect_to new_petowner_session_path
    end
  end

  def params_district
    permitted = params.permit(:district_choosen)
    return permitted[:district_choosen]
  end
end

app/helpers/petsitters_helper.rb
module PetsittersHelper
  def my_petowners(arg)
    return Petowner.find(arg)
  end

  def booking_validate
    Petsitting.find_by(petowner_id: current_petowner.id, petsitter_id: params[:id])
  end

  def petowner_exists(arg)
    return Petowner.find_by(id: arg).blank?
  end

end

app/views/petsitters/_bookings.html.erb
<div class="left pt-1 mr-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12 align-self-center">
        <h4>Mes réservations</h4>
      </div>
    </div>
  </div>
</div>
<br>
<div class="divider divider-grad"></div>
<section>
  <div class="container shadow-lg rounded">
    <div class="col-sm-12 col-md-12 ">
      <ul class="nav nav-tabs tab-with-center-icon justify-content-center nav-justified">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#tab-8-1"> <i class="ti-time"></i>Mes nouvelles réservations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#tab-8-2"> <i class="ti-check-box"></i>Pet Sittings validés</a>
        </li>
      </ul>
        <div class="tab-content">
          <!-- VALIDATIONS EN ATTENTE, FIRST TAB -->
          <%= render 'tab_booking_pending' %>

          <!-- PET SITTINGS VALIDÉS, SECOND TAB -->
          <%= render 'tab_booking_validate' %>
        </div>
      </div>
    </div>
</section>

app/views/petsitters/_card_petsitters.html.erb
  <div class="row">
    <!-- ITEM -->
    <% @petsitters.shuffle.each do |petsitter| %>
      <% if petsitter.account_validate == true %>
        <div class="item pb-5 col-sm-4">
          <div class="post">
            <%= image_tag petsitter.avatar, alt: 'avatar' , class:'shadow-lg avatar-card'%>
            <div class="post-info ">
              <% petsitter.districts.each do |district| %>
                <span class="post-tag bg-grad text-white mb-3 clearfix"><%= district.district_name %></span>
              <% end %>
              <span class="post-price bg-grad text-white clearfix"><%= petsitter.price %> €/jours</span>
              <div class="post-author"><%= petsitter.first_name %> <%= petsitter.last_name %></div>
              <!-- HELPER POUR RECHERCHE LES COMMENTAIRES D'UN PETSITTER -->
              <div class="post-time float-right"><%= comments_petsitter(petsitter.id).count %>  <i class="fa fa-comment"></i></div>

              <div class="post-title text-primary"><%= petsitter.describe %></div>
            </div>
            <div class="d-flex justify-content-around flex-md-wrap mt-auto p-2 bd-highligh">
              <%= link_to petsitter_path(petsitter.id) do %>
                <span class="btn btn-info"><i class="fa fa-bullseye"></i>Son profil !</span>
              <% end %>
              <% if current_petowner %>
                <% if petsitter.email != current_petowner.email %>
                  <%= form_with(url: petsittings_path, method: 'post') do%>
                    <%= hidden_field_tag(name='id', petsitter.id) %>
                    <%= button_tag(type: "submit",  class:"btn btn-grad") do %>
                      <span><i class="fa fa-envelope-o"></i>Contacter</span>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/petsitters/_card_petsitters_JS.html.erb
  <div class="row">
    <!-- ITEM -->
    <% petsitter_district.shuffle.each do |petsitter| %>
      <% if petsitter.account_validate == true %>
        <div class="item pb-5 col-sm-4">
          <div class="post">
            <%= image_tag petsitter.avatar, alt: 'avatar' , class:'shadow-lg avatar-card'%>
            <div class="post-info ">
              <% petsitter.districts.each do |district| %>
                <span class="post-tag bg-grad text-white mb-3 clearfix"><%= district.district_name %></span>
              <% end %>
              <span class="post-price bg-grad text-white clearfix"><%= petsitter.price %> €/jours</span>
              <div class="post-author"><%= petsitter.first_name %> <%= petsitter.last_name %></div>
              <!-- HELPER POUR RECHERCHE LES COMMENTAIRES D'UN PETSITTER -->
              <div class="post-time"><%= comments_petsitter(petsitter.id).count %></div>

              <div class="post-title text-primary"><%= petsitter.describe %></div>
            </div>
            <div class="d-flex justify-content-around flex-md-wrap mt-auto p-2 bd-highligh">
              <%= link_to petsitter_path(petsitter.id) do %>
                <span class="btn btn-info"><i class="fa fa-bullseye"></i>Son profil !</span>
              <% end %>
              <% if current_petsitter == nil || petsitter.email != current_petowner.email%>
                <%= form_with(url: petsittings_path, method: 'post', local: true) do%>
                  <%= hidden_field_tag(name='id', petsitter.id) %>
                  <%= button_tag(type: "submit",  class:"btn btn-grad") do %>
                    <span><i class="fa fa-envelope-o"></i>Contacter</span>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/petsitters/_private_profil.html.erb
<div class="left pt-1 mr-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12 align-self-center">
        <h4>Mon Profil</h4>
      </div>
    </div>
  </div>
</div>
<br>
<div class="divider divider-grad"></div><br>
  <span class="pt-0 h5">
    <p><span class= "font-weight-bold">Identité :</span> <%= @petsitter.first_name %> <%= @petsitter.last_name %></p>
    <p><span class= "font-weight-bold">Âge :</span> <%= @petsitter.age %></p>
    <p><span class= "font-weight-bold">Numéro de télephone :</span> <%= @petsitter.phone_number %></p>
    <p><span class= "font-weight-bold">Email :</span> <%= @petsitter.email %></p>
    <p><span class= "font-weight-bold">Quartier :</span> <%= @district.district_name %></p><br>

    <div class="divider divider-grad"></div><br>

    <p><span class= "font-weight-bold">Jardin :</span>
      <% if @petsitter.garden == true %>
        Oui
      <% else %>
        Non
      <% end %></p>
    <p><span class= "font-weight-bold">Surface habitable :</span> <%= @petsitter.living_space %> m2</p>
    <p><span class= "font-weight-bold">Prix par jour :</span> <%= @petsitter.price %> €</p>

  </span>
  <div>
    <%= link_to edit_petsitter_registration_path do %>
    <button type="button" class="btn btn-button btn-dark mr-4 mb-3 mb-sm-0">Editer votre compte </button>
    <% end %>
  </div>

app/views/petsitters/_profil.html.erb
<div class="left pt-1 mr-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12 align-self-center">
        <h4>Bienvenue sur ma page !</h4>
      </div>
    </div>
  </div>
</div>
<br>
<div class="divider divider-grad"></div><br>

<h5 class="display-6 display-4 font-weight-normal cd-headline clip clip-dark big-clip is-full-width">
  <span class="pt-0 h5">
    <p><span class= "font-weight-bold">Nom : </span> <%= @petsitter.first_name %> <%= @petsitter.last_name %></p>
      <% if current_petsitter || booking_validate %>
        <p><span class= "font-weight-bold">Numéro de télephone : </span> <%= @petsitter.phone_number %></p>
        <p><span class= "font-weight-bold">Email :</span> <%= @petsitter.email %></p>
      <% end %>
  </span><br>
  <span class="pt-0">Je vous propose de garder vos:</span><br>
  <span class="cd-words-wrapper pt-0 text-primary">
    <b class="is-visible">Chiens</b>
    <b>Chats</b>
    <b>Tarentules</b>
  </span>
</h5>
<div class="col-md-12 mb-4">
  <blockquote class="blockquote grad-line">
    <p class="h5 text-light-gray mb-4 font-weight-normal"><%= @petsitter.describe %></p>
  </blockquote>
</div>
<% if current_petowner && @petsitter.email != current_petowner.email %>
  <%= form_with(url: petsittings_path, method: 'post', local: true) do%>
    <%= hidden_field_tag(name='id', @petsitter.id) %>
    <%= button_tag(type: "submit", class: "btn btn-default") do %>
      <span class="btn btn-info"><i class="fa fa-envelope-o"></i>Contacter</span>
    <% end %>
  <% end %>
<% end %>
<div class="divider divider-grad"></div><br>
<% if current_petsitter %>
  <% if current_petsitter.id == @petsitter.id %>
    <span>
      <p>Il n'y a pas encore d'avatar lié à ce compte !</p>
      <%= form_tag petsitter_avatars_path(@petsitter), multipart: true do %>
        <%= file_field_tag :avatar %>
        <%= button_tag(type: 'submit', class:"btn btn-success") do %>
          <span><i class="fa fa-check-circle-o""></i>Mettre à jour</span>
        <% end %>
      <% end %>
    </span>
  <% end %>
<% end %>

app/views/petsitters/_tab_booking_pending.html.erb
<div class="tab-pane show active" id="tab-8-1">
  <div class="col-sm-12 mb-5">
    <div class="table-responsive">
      <table class="table table-lg table-noborder table-striped">
        <thead class="all-text-white bg-grad">
          <tr class="text-white">
            <th scope="col"> </th>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Mail</th>
            <th scope="col">Réservation</th>
          </tr>
        </thead>
        <tbody>
          <!-- methode my_petowners => helper -->
          <% if @bookings.nil? %>
          <% else %>
            <% @bookings.each do |booking|%>
            <% if booking.validate_petsitter == false %>
                <tr id="booking-f-<%= booking.id %>">
                  <!-- VERIFICATION SI LE PETSITTERS EXISTE TOUJOURS EN BASE DE DONNÉES -->
                  <% if petowner_exists(booking.petowner_id) == false %>

                    <td class="d-flex justify-content-around align-items-center flex-md-wrap">
                      <%= link_to petowner_path(booking.petowner_id) do %>
                        <span class="btn btn-info">Profil</span>
                      <%end%>
                      <%= form_with(url: petsitting_path(booking.id), method:'patch', remote: true) do%>
                        <%= button_tag(type: "submit", class: "btn btn-grad") do %>
                          <span>Confirmer</span>
                        <%end%>
                      <% end %>
                      <%= link_to petsitting_path(booking.id),local:true, data: { confirm: "Etes-vous sur de vouloir annuler ce rendez-vous ?"}, :method => :delete do %>
                        <i class="fa fa-trash fa-2x ml-1" aria-hidden="true"></i>
                      <% end %>
                    </td>

                    <td><%= my_petowners(booking.petowner_id).first_name%> </td>
                    <td><%= my_petowners(booking.petowner_id).last_name%> </td>
                    <td><%= my_petowners(booking.petowner_id).email%> </td>
                    <td><%= booking.updated_at.strftime("%d-%m-%Y")%></td>

                  <!-- AFFICHAGE SI UN PO A SUPPRIMÉ SON COMPTE -->
                  <% else %>

                    <td class="d-flex justify-content-around align-items-center flex-md-wrap">
                    <%= link_to petsitting_path(booking.id),local:true, data: { confirm: "Etes-vous sur de vouloir annuler ce rendez-vous ?"}, :method => :delete do %>
                      <i class="fa fa-trash fa-2x ml-1" aria-hidden="true"></i>
                    <% end %>
                    </td>
                    <td><i class='small'> Utilisateur supprimé </i> </td>
                    <td><i class='small'> Utilisateur supprimé </i></td>
                    <td><i class='small'> Utilisateur supprimé </i></td>
                    <td><i class='small'> Utilisateur supprimé </i></td>
                  <%end%>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/petsitters/_tab_booking_validate.html.erb
<div class="tab-pane" id="tab-8-2">
  <div class="col-sm-12 mb-5">
    <div class="table-responsive">
      <table class="table table-lg table-noborder table-striped">
        <thead class="all-text-white bg-grad">
          <tr class="text-white">
            <th scope="col"> </th>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Mail</th>
            <th scope="col">Réservation</th>
          </tr>
        </thead>
        <tbody class="booking">
          <!-- methode my_petowners => helper -->
          <% if @bookings.nil? %>
          <% else %>
            <% @bookings.each do |booking|%>
              <% if booking.validate_petsitter == true %>
                <tr>
                  <!-- VERIFICATION SI LE PETSITTERS EXISTE TOUJOURS EN BASE DE DONNÉES -->
                  <% if petowner_exists(booking.petowner_id) == false %>
                    <td class="d-flex justify-content-around align-items-center flex-md-wrap">
                      <%= link_to petowner_path(booking.petowner_id) do %>
                        <span class="btn btn-info">Profil</span>
                      <%end%>
                      <% if booking.validate_petowner == false %>
                      <span class="btn btn-secondary"> En attente </span>
                      <% else %>
                      <span class="btn btn-grad"> Validée</span>
                      <%end %>
                      <% unless booking.validate_petowner == true && booking.validate_petsitter == true%>
                      <%= link_to petsitting_path(booking.id),local:true, data: { confirm: "Etes-vous sur de vouloir annuler ce rendez-vous ?"}, :method => :delete do %>
                        <i class="fa fa-trash fa-2x ml-1" aria-hidden="true"></i>
                      <%end%>
                      <% end %>
                    </td>
                    <td><%= my_petowners(booking.petowner_id).first_name%> </td>
                    <td><%= my_petowners(booking.petowner_id).last_name%> </td>
                    <td><%= my_petowners(booking.petowner_id).email%> </td>
                    <td><%= booking.updated_at.strftime("%d-%m-%Y")%></td>

                    <!-- AFFICHAGE SI UN PO A SUPPRIMÉ SON COMPTE -->
                  <% else %>

                    <td class="d-flex justify-content-around align-items-center flex-md-wrap">
                    <%= link_to petsitting_path(booking.id),local:true, data: { confirm: "Etes-vous sur de vouloir annuler ce rendez-vous ?"}, :method => :delete do %>
                      <i class="fa fa-trash fa-2x ml-1" aria-hidden="true"></i>
                    <% end %>
                    </td>
                    <td><i class='small'> Utilisateur supprimé </i> </td>
                    <td><i class='small'> Utilisateur supprimé </i></td>
                    <td><i class='small'> Utilisateur supprimé </i></td>
                    <td><i class='small'> Utilisateur supprimé </i></td>
                  <%end%>
                </tr>
              <%end%>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/petsitters/index.html.erb
<div class="blog bg-light">
	<div class="container" >
		<div class="row">
			<div class="col-12 col-lg-10 mx-auto mt-6">
				<div class="title text-center">
					<h3>Trouvez et réservez le Pet Sitter de votre choix. </h3>
				</div>
			</div>
		</div><br>

		<br><div class="divider"><i class="ti-info-alt"></i> </div><br><br>
		<div class="row">
			<div class="col-md-4 mt-4">
				<div class="feature-box f-style-4 h-100 icon-grad">
					<div class="feature-box-icon"><i class="ti-search"></i></div>
					<h3 class="feature-box-title">Recherchez</h3>
					<p class="feature-box-desc">Trouvez le Pet Sitter de votre choix dans le quartier le plus proche de chez vous ! N'hésitez pas à consulter leur profil !</p>
				</div>
			</div>
			<div class="col-md-4 mt-4">
				<div class="feature-box f-style-4 h-100 icon-grad">
					<div class="feature-box-icon"><i class="ti-comments-smiley"></i></div>
					<h3 class="feature-box-title">Discutez</h3>
					<p class="feature-box-desc">Après avoir cliqué sur "Contacter", échangez avec votre pet sitter pour convenir des dates de gardiennages et du prix en contrepartie !</p>
				</div>
			</div>
			<div class="col-md-4 mt-4">
				<div class="feature-box f-style-4 h-100 icon-grad">
					<div class="feature-box-icon"><i class="ti-thumb-up"></i></div>
					<h3 class="feature-box-title">C'est parti !</h3>
					<p class="feature-box-desc">Votre petite boules de poiles est entre de bonnes mains</p>
				</div>
			</div>
		</div>
		<br><br><div class="divider mb-5"><i class="ti-search"></i> </div>


		<div id="flash_position"></div>

		<!-- NARBAR RECHERCHE PAR QUARTIER -->
		<div class="form-inline justify ml-3">
			<%= form_with( method: 'get') do %>
				<%= select_tag(:district_choosen, options_from_collection_for_select(@districts, :id, :district_name), class:"custom-select select-big mb-3")%>
				<%= button_tag(type: "submit", class: "btn btn-default") do %>
					<span class="btn btn-grad">Filtrer</span>
				<% end %>
			<% end %>
		</div>

    <!-- CARDS -->
		<div class="container" id='card_petsitters'>
    	<%= render 'card_petsitters' %>
		</div>
	</div>
</div>

<%= render "layouts/button_back_index"%>

app/views/petsitters/index.js.erb
$(document).ready(function() {
  console.log('<%= @petsitters_district %>');

  <% if @params_district == '1' %>
    $('#card_petsitters').hide().html("<%= j render 'card_petsitters' %>").fadeIn('slow');
  <% else %>
    <% if @petsitters_district.empty? || @validate_petsitters.empty? %>
      <% flash.now[:alert] = 'Il semblerait que la recherche ne donne rien..' %>
      $('#card_petsitters').hide().html("<%= j render 'layouts/flash_alert' %>").fadeIn('slow')
    <% else %>
      <% if !@selected_district.empty? %>
        $('#card_petsitters').hide().html("<%= j render 'card_petsitters_JS', petsitter_district: @petsitters_district %>").fadeIn('slow');

      <% else %>
        <% flash.now[:alert] = 'Il semblerait que la recherche ne donne rien..' %>
        $('#card_petsitters').hide().html("<%= j render 'layouts/flash_alert' %>").fadeIn('slow')
      <% end %>
    <% end %>
  <%end%>
});

app/views/petsitters/show.js.erb
$(document).ready(function() {
console.log("123")
$('#booking-f-'<% booking.id).html.fadeOut("slow");
});