config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'staticpages#index'
  get 'team', to: 'staticpages#team'
  get '404' , to: "errors#not_found"
  get '422' , to: "errors#unacceptable"
  get '500' , to: "errors#internal_error"


  resources :charges

  devise_for :petsitters,  path: 'petsitters', controllers: { sessions: "petsitters/sessions", registrations: "petsitters/registrations", passwords: "petsitters/passwords"}
  devise_for :petowners, path: 'users', controllers: { sessions: "petowners/sessions", registrations: "petowners/registrations", passwords: "petowners/passwords"}
  resources :petsitters, only: [:show, :index] do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :petowners, only: [:show], path: 'profil' do
    resources :avatars, only: [:create]
  end

  resources :pets, only: [:new, :create] do
    resources :avatars, only: [:create]
  end
  resources :organizations, only: [:show, :index, :new, :create], :path => "associations"
  resources :petsittings, only: [:new, :create, :show, :update, :destroy]
  resources :contacts, only: [:new, :create]
  resources :comments, only: [:new, :create, :index]

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def team
  end

  def index

  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/staticpages/_cardteam.html.erb
<section class="team social-hover team-overlay">
	<div class="container">
		<div class="row">
			<!-- Team item -->
			<div class="col-12 col-sm-3 col-md-3">
				<div class="team-item text-center animated bounce">
					<div class="team-avatar">
						<%= image_tag "team/Poupou.jpeg", class: "team-card" %>
					</div>
					<div class="team-desc">
						<h5 class="team-name">Marine El Adouzi</h5>
						<span class="team-position">Préfère les chats</span>
						<p>I am temporibus voluptatem odio odit ratione perferendis explicabo!</p>
						<ul class="social-icons si-colored-on-hover">
							<li class="social-icons-item social-twitter"><%= link_to "https://twitter.com/meladouz", class:"social-icons-link" do%><i class="fa fa-twitter fa-2x"></i><%end%></li>
						</ul>
					</div>
				</div>
			</div>
			<!-- Team item -->
			<div class="col-12 col-sm-3 col-md-3">
				<div class="team-item text-center animated bounce ">
					<div class="team-avatar">
						<%= image_tag "team/Maya.jpeg" , class: "team-card"%>
					</div>
					<div class="team-desc">
						<h5 class="team-name">Paul Hennin</h5>
						<span class="team-position">Préfère les chats</span>
						<p>Expert in temporibus voluptatem odio odit ratione perferendis explicabo!</p>
						<ul class="social-icons si-colored-on-hover">
							<li class="social-icons-item social-instagram"><%= link_to "https://instagram.com/paul_aux_mangas", class:"social-icons-link" do%><i class="fa fa-instagram fa-2x"></i><%end%></li>
						</ul>
					</div>
				</div>
			</div>
			<!-- Team item -->
			<div class="col-12 col-sm-3 col-md-3">
				<div class="team-item text-center animated bounce ">
					<div class="team-avatar">
						<%= image_tag "team/nola.jpeg", class: "team-card" %>
					</div>
					<div class="team-desc">
						<h5 class="team-name">Jordi Le Guet</h5>
						<span class="team-position">Préfère les chats</span>
						<p>Have more then 8 years temporibus voluptatem odio odit ratione perfere!</p>
						<ul class="social-icons si-colored-on-hover">
							<li class="social-icons-item social-twitter"><%= link_to "https://twitter.com/YorudeO", class:"social-icons-link" do%><i class="fa fa-twitter fa-2x"></i><%end%></li>
						</ul>
					</div>
				</div>
			</div>
			<!-- Team item -->
			<div class="col-12 col-sm-3 col-md-3">
				<div class="team-item text-center animated bounce ">
					<div class="team-avatar">
						<%= image_tag "team/Neji.jpeg", class: "team-card" %>
					</div>
					<div class="team-desc">
						<h5 class="team-name">Terence Le Guet</h5>
						<span class="team-position">Préfère les chiens</span>
						<p>With more then temporibus voluptatem odio odit ratione perferendis!</p>
						<ul class="social-icons si-colored-on-hover">
							<li class="social-icons-item social-twitter"><%= link_to "https://twitter.com/TT81269634", class:"social-icons-link" do%><i class="fa fa-twitter fa-2x"></i><%end%></li>
						</ul>
					</div>
				</div>
			</div>
    </div>
  </div>
</section>

app/views/staticpages/contact.html.erb
<div class="text-center bg-overlay-dark-4" style="background:url(assets/images/bg/05.jpg) no-repeat; background-size: cover; background-position: center center;">
		<div class="container">
			<div class="row all-text-white">
				<div class="col-md-12 align-self-center">
					<h6 class="display-6 mt-9 mb-0">Appelez-nous au +334 01 20 03 40</h6>
					<h1 class="font-weight-bold display-4 display-md-1 mb-2 mb-md-n4">Nous contacter</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- =======================
	Banner innerpage -->

	<!-- =======================
	contact -->
	<section class="contact-page">
		<div class="container">
			<div class="row">
				<div class="col-12 col-lg-8 mx-auto">
					<div class="title text-center">
						<h2>En quoi pouvons-nous vous aider ?</h2>
						<p>Toute l'équipe d'Un gardien près de chez soi vous répondra dans les meilleurs délais</p>
					</div>
				</div>
			</div>
			<div class="row ">
				<div class="col-md-3 mb-5">
					<div class="contact-box h-100 bg-overlay-dark-7 px-3 py-4" style="background:url(assets/images/bg/04.jpg) no-repeat; background-size: cover; background-position: center center; ">
						<!-- Phone -->
						<div class="contact-info all-text-white">
							<div class="contact-box-icon"><i class="ti-map-alt"></i></div>
							<h5 class="mb-2">Adresse</h5>
							<p>L'Anacrouse, 34000 Montpellier</p>
						</div>
						<!-- Email -->
						<div class="contact-info all-text-white">
							<div class="contact-box-icon"><i class="ti-email"></i></div>
							<h5 class="mb-2">E-mail</h5>
							<p>help@wizixo.com</p>
						</div>
						<!-- Phone -->
						<div class="contact-info all-text-white">
							<div class="contact-box-icon"><i class="ti-panel"></i></div>
							<h5 class="mb-2">Téléphone</h5>
							<p>+334 01 20 03 40</p>
						</div>
					</div>
				</div>
				<!-- google map -->
				<div class="col-md-3 mb-5">
					<div class="h-100">
						<div class="contact-map o-hidden">
							<div class="map-wrapper" id="map-dark" data-lat="43.6105009" data-lng="3.87441793" data-string="L'Anacrouse, 5, Place du Petit Scel, Montpellier 34000" data-zoom="15">
              </div>
						</div>
					</div>
				</div>
				<!-- contact form -->
				<div class="col-md-6">
					<div class="h-100">
						<h3>Une suggestion pour le site ?</h3>
						<p>Le formulaire ci-dessous nous permettra de rester en contact !</p>
						<form class="contact-form" id="contact-form" name="contactform" action="assets/include/contact-action.php">
							<!-- Start form message -->
							<div class="row">
								<div class="col-12">
									<div class="alert alert-success contact-msg" style="display: none" role="alert">
										Your message was sent successfully.
									</div>
								</div>
							</div>
							<!-- End form message -->

							<!-- Start main form -->
							<div class="row">
								<div class="col-md-6">
									<!-- name -->
									<span class="form-group">
										<input id="con-name" name="name" type="text" class="form-control" placeholder="Name">
									</span>
								</div>
								<div class="col-md-6">
									<!-- email -->
									<span class="form-group">
										<input id="con-email" name="email" type="email" class="form-control" placeholder="E-mail">
									</span>
								</div>
								<div class="col-md-12">
									<!-- Subject -->
									<span class="form-group">
										<input id="con-subject" name="subject" type="text" class="form-control" placeholder="Subject">
									</span>
								</div>
								<div class="col-md-12">
									<!-- Message -->
									<span class="form-group">
										<textarea id="con-message" name="message" cols="40" rows="6" class="form-control" placeholder="Message"></textarea>
									</span>
								</div>
								<!-- submit button -->
								<div class="col-md-12 text-center"><button class="btn btn-dark btn-block">Send Message</button></div>
							</div>
							<!-- End main form -->
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- =======================
	contact -->

	<!-- =======================
	more-info -->
	<section class="pt-0">
		<div class="container ">
			<div class="row justify-content-md-center">
				<div class="col-md-4 text-center">
					<h5 class="mb-1"> Communication</h5>
					<p>Pour toute demande, incluant des partenariats professionnels, nous contacter par mail: <%= mail_to 'ungardienpresdechezsoi@gmail.com'%></p>
				</div>
			</div>
		</div>
	</section>
	<!-- =======================
	more-info -->

  	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtF5lHSU7Y7c2BYl_c4-G9bSi44h1X9Ls"></script>

app/views/staticpages/index.html.erb
<body>
<!-- Index Banner -->
	<section class ="p-0">
		<div class="swiper-container height-700-responsive swiper-arrow-hover swiper-slider-fade">
			<div class="swiper-wrapper">
				<!-- slide 1-->
				<div class="swiper-slide bg-overlay-dark-2 index_slide_1">
					<div class="container h-100">
						<div class="row d-flex h-100">
							<div class="col-lg-8 col-xl-6 mr-auto slider-content justify-content-center align-self-center align-items-start text-left">
								<h3 class="animated fadeInUp dealy-1000 text-white display-8 display-md-7 alt-font font-italic mb-2 my-md-4">Vous partez en vacances ? <br> Vous cherchez un gardien pour vos animaux sur Montpellier ?</h3>
								<h2 class="animated fadeInUp dealy-500 display-6 display-md-4 display-lg-3 font-weight-bold text-white">Découvrez&nbsples&nbspPet&nbspSitters <br> près&nbspde&nbspchez&nbspvous&nbsp!</h2>
								<div class="animated fadeInUp mt-3 dealy-1500">
									<%= link_to petsitters_path do %>
                		<span class="btn btn-grad btn-lg">Trouver un Pet Sitter !</span>
                  <%end%>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- slide 2-->
				<div class="swiper-slide bg-overlay-dark-2 index_slide_2">
					<div class="container h-100">
						<div class="row d-flex h-100">
							<div class="col-md-8 justify-content-center align-self-center align-items-start mx-auto">
								<div class="slider-content text-center ">
									<h3 class="animated fadeInUp dealy-500 display-8 display-md-7 text-white alt-font font-italic">Vous aimez les animaux ? <br> Vous habitez à Montpellier ?</h3>
									<h2 class="animated fadeInUp dealy-1000 display-6 display-md-4 display-lg-3 font-weight-bold text-white">Devenez&nbspPet&nbspSitter&nbsp!</h2>
									<div class="animated fadeInUp mt-3 dealy-1500">
										<%= link_to new_petsitter_registration_path do %>
                  		<span class="btn btn-grad btn-lg">Déposer une demande</span>
                  	<%end%>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Slider buttons -->
			<div class="swiper-button-next"><i class="ti-angle-right"></i></div>
			<div class="swiper-button-prev"><i class="ti-angle-left"></i></div>
			<div class="swiper-pagination"></div>
		</div>
	</section>

  <section class="mt-lg-n9 mt-sm-0 pb-0 z-index-9">
  	<div class="container ">
  		<div class="row bg-white shadow m-0 p-2 p-lg-5 border-radius-3">
        <div class="row col-md-12 ">
          <h2 class="col-md-12 mb-5 cd-headline zoom text-center ">
						<span>Faire garder votre animal devient</span>
						<span class="cd-words-wrapper pt-0">
							<b class="is-visible">Simple</b>
							<b>Rapide</b>
						</span>
					</h2>
        </div>
        <div class="row">
    			<div class="col-md-4">
    				<div class="feature-box h-100 text-center">
    					<div class="feature-box-icon  icon-grad">
              	<i class="fa fa-home fa-2x"></i>
              </div>
    						<h3 class="feature-box-title">Cherchez un Pet Sitter <br>près de chez vous</h3>
    						<h6 class="feature-box-desc text-muted">Recherchez parmis les quartiers de Montpellier, un gardien pour vos animaux de compagnie.</h6>
    				</div>
    			</div>
    			<div class="col-md-4">
    				<div class="feature-box h-100 text-center">
    					<div class="feature-box-icon  icon-grad">
                <i class="fa fa-comment fa-2x"></i>
              </div>
    					<h3 class="feature-box-title">Contacter et échanger <br> avec un Pet Sitter</h3>
    					<h6 class="feature-box-desc text-muted">Une fois inscrit, échangez avec le gardien afin de définir les modalités de gardiennage.</h6>
    				</div>
    			</div>
    			<div class="col-md-4">
    				<div class="feature-box h-100 text-center">
    					<div class="feature-box-icon  icon-grad index_color">
              	<i class="fa fa-heart-o fa-2x"></i>
              </div>
    					<h3 class="feature-box-title">Vous pouvez partir <br>l'esprit tranquille !</h3>
    					<h6 class="feature-box-desc text-muted">Nos Pet Sitters sont sélectionnés pour vous garantir un service de qualité ! </h6>
    				</div>
    			</div>
        </div>
  		</div>
  	</div>
  </section>

<!-- Petsitters qualification-->
	<section>
		<div class="container">
			<div class="row class">
				<div class="col-sm-6 d-none d-lg-block">
          <%= image_tag "index/trusted.jpeg", class: 'border-radius-5 shadow' %>
				</div>
				<div class="col-lg-6 pl-3 pl-md-5">
					<h2 class="mb-4 h1">Pourquoi choisir nos Pet Sitters ? <br> Un gage de confiance ! </h2>
					<h3 class="lead text-muted">Attentif au bien-être de vos animaux, nos Pet Sitters sont sélectionnés pour vous assurer des vacances en toute tranquilité en sachant votre animal en sécurité et chouchouté ! </h3>
					<div class="mt-5">
						<div class="feature-box mt-3 f-style-4 h-100 icon-grad">
							<div class="feature-box-icon"><i class="fa fa-check-circle-o"></i></div>
							<h3 class="feature-box-title mb-0">Garantie d'une garde en toute sécurité</h3>
							<h4 class="feature-box-desc text-muted">A travers un dossier très complet, nos Pet Sitters doivent nous garantir leurs qualifications pour la garde d'animaux. Nous vérifions également l'identité de nos Pet Sitters ainsi que les conditions d'hébergement.</h4>
						</div>
						<div class="feature-box mt-3 f-style-4 h-100 icon-grad">
							<div class="feature-box-icon"><i class="fa fa-paw"></i></div>
							<h3 class="feature-box-title mb-0">Plus de culpabilité !</h3>
							<h4 class="feature-box-desc text-muted">Partez en vacances ou en week-end l'esprit tranquille, une personne de confiance s'occupe de vos animaux !</h4>
						</div>
						<div class="feature-box mt-3 f-style-4 h-100 icon-grad">
							<div class="feature-box-icon"><i class="fa fa-smile-o"></i></div>
							<h3 class="feature-box-title mb-0">Votre animal sera heureux !</h3>
							<h4 class="feature-box-desc text-muted">Durant vos absences, votre animal aura toujours une personne bienveillante pour s'occuper de lui !</h4>
						</div>
          </div >
				</div>
			</div>
		</div>
	</section>

				
				
			</div>
			</div>
<!--Call to action-->
	<section class="bg-dark pricing pricing-dark pricing-center all-text-white">
		<div class="container">
			<div class="row">
				<div class="col-md-10 mx-auto">
					<h2 class="h1">Trouvez un gardien pour vos animaux <br> dès maintenant !</h2>
				</div>
      </div>
    <div class="row">
			<div class="col-12 mx-auto text-center mt-5">
				<%= link_to petsitters_path do %>
        	<span class="btn btn-grad btn-lg text-white mb-0 mt-3 center-block">Voir les annonces !</span>
        <%end%>
			</div>
		</div>
	</section>
	<!-- Call to action-->


<!-- Associations -->
	<section class="parallax-bg bg-overlay-dark-2 index_association">
		<div class="container">
			<div class="row">
				<div class="col-md-5 mt-30">
					<div class=" bg-dark feature-box f-style-2 h-100 icon-grad rounded">
						<div class="feature-box-icon"><i class="fa fa-paw"></i></div>
						<h3 class="feature-box-title text-white">Pas encore d'animaux à vous ? <br> Vous pouvez adopter !</h3>
						<h5 class="feature-box-desc text-white">De nombreuses associations sur Montpellier vous permettrons de recueillir des animaux abandonnés qui ne demandent qu'à trouver une famille. </h5>
          	<div class=" d-flex float-right">
            	<%= link_to organizations_path do %>
              	<span class="btn btn-primary mb-0 mt-3">Plus d'infos</span>
            	<%end%>
          	</div>
					</div>
				</div>
			</div>
		</div>
	</section>
<!-- Associations -->
</body>

app/views/staticpages/team.html.erb
<div class="bg-overlay-dark-2 parallax-bg pt-7 pb-10 team-banner">
  <div class="position-absolute bottom-0 left-0 w-100 mb-n3">
    <svg width="100%" height="150" viewBox="0 0 500 150" preserveAspectRatio="none">
      <path d="M0,150 L0,40 Q250,150 500,40 L580,150 Z" fill="white" />
    </svg>
  </div>
</div>
<%= render 'cardteam' %>