config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'staticpages#index'
  get 'team', to: 'staticpages#team'
  get '404' , to: "errors#not_found"
  get '422' , to: "errors#unacceptable"
  get '500' , to: "errors#internal_error"


  resources :charges

  devise_for :petsitters,  path: 'petsitters', controllers: { sessions: "petsitters/sessions", registrations: "petsitters/registrations", passwords: "petsitters/passwords"}
  devise_for :petowners, path: 'users', controllers: { sessions: "petowners/sessions", registrations: "petowners/registrations", passwords: "petowners/passwords"}
  resources :petsitters, only: [:show, :index] do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :petowners, only: [:show], path: 'profil' do
    resources :avatars, only: [:create]
  end

  resources :pets, only: [:new, :create] do
    resources :avatars, only: [:create]
  end
  resources :organizations, only: [:show, :index, :new, :create], :path => "associations"
  resources :petsittings, only: [:new, :create, :show, :update, :destroy]
  resources :contacts, only: [:new, :create]
  resources :comments, only: [:new, :create, :index]

end

app/models/petowner.rb
class Petowner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
#  has_many_attached :pets_album
  has_many :pets

  has_many :petsittings
  has_many :petsitters, through: :petsittings

  belongs_to :district
  has_many :comments

  # after_create :welcome_send

  validates :first_name, presence: true, length: { minimum: 3 }
  validates :last_name, presence: true, length: { minimum: 3 }
  validates :describe, presence: true, length: { in: 20..1000 }
  validates :age, presence: true
  validates :phone_number, presence: true, format: { with: /\A(?:(?:\+|00)33[\s.-]{0,3}(?:\(0\)[\s.-]{0,3})?|0)[1-9](?:(?:[\s.-]?\d{2}){4}|\d{2}(?:[\s.-]?\d{3}){2})\z/, message: "Entrer un numero de telephone valide" }


  def welcome_send
    PetownerMailer.welcome_email(self).deliver_now
      @petowner = self
      @petowner.avatar.attach(io: File.open('./app/assets/images/avatar_default/default_avatar.jpg'), filename:"avatar.jpg")
      @petowner.save
  end

end

app/controllers/petowners/confirmations_controller.rb
# frozen_string_literal: true

class Petowners::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/petowners/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Petowners::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/petowners/passwords_controller.rb
# frozen_string_literal: true

class Petowners::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/petowners/registrations_controller.rb
# frozen_string_literal: true

class Petowners::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :describe, :age, :phone_number, :district_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :describe, :age, :phone_number, :district_id])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/petowners/sessions_controller.rb
# frozen_string_literal: true

class Petowners::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/petowners/unlocks_controller.rb
# frozen_string_literal: true

class Petowners::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/petowners_controller.rb
class PetownersController < ApplicationController
  before_action :signed_in , only: [:show]

  def show
    @petowner = Petowner.find(params[:id])
    @pets = pets_of_current_petowner

    if current_petowner
      @bookings_petowner = Petsitting.where(petowner_id: current_petowner.id)
    end

  end

private

  def pets_of_current_petowner
    Pet.where(petowner_id: (params[:id]))
  end

  def signed_in
    if current_petsitter
      @petsitting = Petsitting.find_by(petsitter_id: current_petsitter.id)
      @petowner = Petowner.find(params[:id])
      if current_petsitter.nil?
      redirect_to new_petowner_session_path
      end
      if @petsitting.petowner_id != @petowner.id
        redirect_to root_path
      end
    end

    if current_petowner
      if current_petowner.id != Petowner.find(params[:id]).id
        redirect_to petowner_path(current_petowner.id)
      end
    end

    rescue ActiveRecord::RecordNotFound
      redirect_to root_url
      flash.now[:success] = "La page que vous avez demandé n'existe pas !"
    end
end

app/helpers/petowners_helper.rb
module PetownersHelper
  def my_petsitters(arg)
    return Petsitter.find_by(id: arg)
  end

  def petsitter_exists(arg)
    return Petsitter.find_by(id: arg).blank?
  end
end

app/views/petowners/_bookings.html.erb
<div class="tab-pane" id="tab-3-3">
  <div class="left pt-1 mr-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12 align-self-center">
          <h4>Mes réservations</h4>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="divider divider-grad"></div>
  <% if current_petowner %>
    <% if current_petowner.id == @petowner.id %>
      <section>
        <div class="container shadow-lg rounded">
          <div class="col-sm-12 col-md-12 ">
            <ul class="nav nav-tabs tab-with-center-icon justify-content-center nav-justified">
              <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#tab-8-1"> <i class="ti-time"></i> Demandes de réservations </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#tab-8-2"> <i class="ti-check-box"></i> Pet Sittings validés</a>
              </li>
            </ul>
            <div class="tab-content">
              <!-- FIRST TAB -->
              <%= render 'tab_booking_pending' %>
              <!-- SECOND TAB -->
              <%= render 'tab_booking_validate' %>
            </div>
          </div>
        </div>
      </section>
      <%else%>
    <% end %>
  <% end %>
</div>

app/views/petowners/_my_pets.html.erb
<div class="tab-pane" id="tab-3-2">
  <div class= "container">
    <div class="left pt-1 mr-5">
      <div class="row">
        <div class="col-md-12 align-self-center">
          <h4>Mes animaux</h4>
        </div>
      </div>
    </div>
    <br><div class="divider divider-grad"></div><br>
    <div class="d-flex">
      <div class="row justify-content-around align-items-center w-100">
        <% if current_petowner %>
          <div class="col-md-12 align-self-center text-center">

            <!-- BUTTON MODAL -->
            <button type="button" class="btn btn-grad" data-toggle="modal" data-target="#exampleModalCenter">
              Ajouter le profil d'un animal
            </button>
            <div class="modal fade text-left" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenter" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Entrer les informations concernant votre animal.</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <%= render "petowners/petsform"%>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <div class="container">
          <div class="row p-3 border border-dashed shadow-lg mt-5">
            <% @pets.each do |pet| %>
              <div class="item pb-5 col-4">
                <div class="post">
                  <% if pet.avatar.attached? != false %>
                    <%= image_tag pet.avatar, alt: 'avatar' , class:'shadow-lg pet-img'%>
                  <% end %>
                  <div class="post-info ">
                    <span class="post-tag bg-grad text-white mb-3 clearfix"><%= pet.pet_type%></span>
                    <div class="post-author">
                      <% if pet.sterilized == true %>
                        <p>Stérélisé(e)</p>
                      <% else %>
                        <p>Non stérilisé(e)</p>
                      <%end%>
                    </div>
                    <div class="post-title text-primary">
                      <%= pet.name%><br>
                      <p><%= pet.pet_type%> <%= pet.sex%></p>
                      <% if pet.sterilized == true %>
                        <p>Stérélisé(e)
                      <% else %>
                        Non stérilisé(e)</p>
                      <%end%>
                    </div>
                  </div>
                </div>
                <% if current_petowner %>
                  <% if pet.avatar.attached? == false %>
                    <p>Il n'y a pas encore d'avatar lié à ce compte !</p>
                    <%= form_tag pet_avatars_path(pet), multipart: true do %>
                      <%= file_field_tag :avatar %>
                      <%= submit_tag "Ajouter une photo" %>
                    <% end %>
                  <%else%>
                    <%= form_tag pet_avatars_path(pet), multipart: true do %>
                      <%= file_field_tag :avatar %>
                      <%= button_tag(type: 'submit', class:"btn btn-success") do %>
                        <span><i class="fa fa-check-circle-o""></i>Mettre à jour</span>
                      <% end %>
                    <%end%>
                  <%end%>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/petowners/_petsform.html.erb
<div class="modal-body">
  <%= form_with model: Pet.create, local: true do |form| %>
    <div class="form-group">
      <label>Son nom :</label>
      <%= form.text_field :name, class: "form-control", placeholder: "Son nom"%>
    </div>
    <div class="form-group">
      <label>Quel est son âge ?</label>
      <%= form.number_field :birth_year, min:"0", max:"25", class: "form-control", placeholder: "Age"%>
    </div>
    <div class="form-group">
			<label>Avez vous un chat ou un chien ?</label>
      <%= form.select :pet_type,[["Chat"], ['Chien']], {}, {:class => 'custom-select select-big mb-3'}%>
		</div>
    <div class="form-group">
			<label>Quel est le sexe de votre animal ?</label>
      <%= form.select :sex,[["Mâle"], ['Femelle']], {}, {:class => 'custom-select select-big mb-3'}%>
		</div>
    <div class="form-group">
      <label>Votre animal est-il stérilisé ?</label>
      <%= form.select :sterilized,[['Oui',true], ['Non',false]], {}, {:class => 'custom-select select-big mb-3'}%>
    </div>
    <div class="modal-footer">
      <p><button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button></p>
      <p><%= form.submit "Sauvegarder", class: "btn btn-primary" %></p>
    </div>
  <% end %>
</div>

app/views/petowners/_profil.html.erb
<div class="tab-pane show active" id="tab-3-1">
  <div class="left pt-1 mr-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12 align-self-center">
          <h4>Mon profil</h4>
        </div>
      </div>
    </div>
  </div>
  <br><div class="divider divider-grad"></div><br>
  <h5 class="col-md-8 display-6 display-xl-4 font-weight-normal cd-headline clip clip-dark big-clip is-full-width">
    <span class="pt-0 h5">
      <p><strong>Identité : </strong><%= @petowner.first_name %> <%= @petowner.last_name %></p>
      <p><strong>Email : </strong><%= @petowner.email%></p>
      <p><strong>Numéro de téléphone : </strong><%= @petowner.phone_number%></p>
    </span>
  </h5>
  <div class="col-md-8 mb-4 mr-2">
		<h5 class="mb-4">Description</h5>
		<blockquote class="blockquote grad-line">
    <h5 class="mb-2 "><%= @petowner.describe %></h5>
		</blockquote>
	</div>
  <div class="divider divider-grad"></div><br>
  <% if current_petowner %>
    <% if current_petowner.id == @petowner.id %>
      <span class=>
        <% if @petowner.avatar.attached? == false %>
          <p>Il n'y a pas encore d'avatar lié à ce compte !</p>
          <%= form_tag petowner_avatars_path(@petowner), multipart: true do %>
            <%= file_field_tag :avatar %>
            <%= button_tag(type: 'submit', class:"btn btn-success") do %>
              <span><i class="fa fa-check-circle-o"></i>Ajouter une photo</span>
            <% end %>
          <% end %>
        <%else%>
          <%= form_tag petowner_avatars_path(@petowner), multipart: true do %>
            <%= file_field_tag :avatar, class:"button"%>
            <%= button_tag(type: 'submit', class:"btn btn-success") do %>
              <span><i class="fa fa-check-circle-o"></i>Mettre à jour</span>
            <% end %>
          <%end%>
        <%end%>
      </span>
    <% end %>
  <% end %>
  <%= link_to edit_petowner_registration_path do %>
    <button type="button" class="btn btn-button btn-dark mr-4 mb-3 mb-sm-0 ">Editer votre compte </button>
  <% end %>
</div>

app/views/petowners/_tab_booking_pending.html.erb
<div class="tab-pane show active" id="tab-8-1">
  <div class="col-sm-12 mb-5">
    <div class="table-responsive text-nowrap">
      <table class="table table-noborder table-striped">
        <thead class="all-text-white bg-grad">
          <tr class="text-white">
            <th scope="col"> </th>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Mail</th>
            <th scope="col">Réservation</th>
          </tr>
        </thead>
        <tbody>
          <!-- helper method my_petsitters -->
          <% @bookings_petowner.each do |booking|%>
            <% if booking.validate_petowner == false%>
                <tr id="booking-f-<%= booking.id %>">
                  <!-- CHECK IF PETSITTER EXIST IN DATABASE -->
                  <% if petsitter_exists(booking.petsitter_id) == false %>
                    <td class="d-flex justify-content-around flex-md-wrap">
                      <%= link_to petsitter_path(booking.petsitter_id) do %>
                        <span class="btn btn-info">Profil</span>
                      <%end%>
                      <% if booking.validate_petsitter == true %>
                        <%= form_with(url: petsitting_path(booking.id), method:'patch', remote: true) do%>
                          <%= button_tag(type: "submit", class: "btn btn-grad") do %>
                            <span">Confirmer</span>
                          <%end%>
                        <% end %>
                      <% else %>
                        <span class="btn btn-secondary">En attente</span>
                      <% end %>
                      <%= link_to petsitting_path(booking.id),local:true, data: { confirm: "Etes-vous sur de vouloir annuler ce rendez-vous ?"}, :method => :delete do %>
                        <i class="fa fa-trash fa-2x ml-1" aria-hidden="true"></i>
                      <% end %>
                    </td>
                    <td><%= my_petsitters(booking.petsitter_id).first_name%> </td>
                    <td><%= my_petsitters(booking.petsitter_id).last_name%> </td>
                    <td><%= my_petsitters(booking.petsitter_id).email%> </td>
                    <td>Validé le <%= booking.updated_at.strftime("%d-%m-%Y")%></td>
                  <!-- VIEW IF A PETSITTER DELETED IS ACCOUNT -->
                  <% else %>
                    <td class="d-flex justify-content-around align-items-center flex-md-wrap">
                    <%= link_to petsitting_path(booking.id),local:true, data: { confirm: "Etes-vous sur de vouloir annuler ce rendez-vous ?"}, :method => :delete do %>
                      <i class="fa fa-trash fa-2x ml-1" aria-hidden="true"></i>
                    <% end %>
                    </td>
                    <td><i class='small'> Utilisateur supprimé </i> </td>
                    <td><i class='small'> Utilisateur supprimé </i></td>
                    <td><i class='small'> Utilisateur supprimé </i></td>
                    <td><i class='small'> Utilisateur supprimé </i></td>
                  <% end %>
                </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/petowners/_tab_booking_validate.html.erb
<div class="tab-pane" id="tab-8-2">
  <div class="col-sm-12 mb-5">
    <div class="table-responsive-sm">
      <table class="table table-lg table-noborder table-striped">
        <thead class="all-text-white bg-grad">
          <tr class="text-white">
            <th scope="col"> </th>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Mail</th>
            <th scope="col">Réservation</th>
          </tr>
        </thead>
        <tbody class="booking">
          <!-- helper methode my_petsitters -->
          <% @bookings_petowner.each do |booking|%>
            <% if booking.validate_petowner == true %>
              <tr>
                <!-- CHECK IF PETSITTER ALREADY EXIST IN DATABASE -->
                <% if petsitter_exists(booking.petsitter_id) == false %>
                  <td class="d-flex justify-content-around flex-md-wrap">
                    <%= link_to petsitter_path(booking.petsitter_id) do %>
                      <span class="btn btn-info">Profil</span>
                    <%end%>
                    <span class="btn btn-grad">Validé</span>
                    <% unless booking.validate_petowner == true && booking.validate_petsitter == true%>
                    <%= link_to petsitting_path(booking.id),local:true, data: { confirm: "Etes-vous sur de vouloir annuler ce rendez-vous ?"}, :method => :delete do %>
                      <i class="fa fa-trash fa-2x ml-1" aria-hidden="true"></i>
                    <% end %>
                    <%end%>
                  </td>
                  <td><%= my_petsitters(booking.petsitter_id).first_name%> </td>
                  <td><%= my_petsitters(booking.petsitter_id).last_name%> </td>
                  <td><%= my_petsitters(booking.petsitter_id).email%> </td>
                  <td>Validé le <%= booking.updated_at.strftime("%d-%m-%Y")%></td>

                <!-- VIEW IF A PETSITTER DELETED IS ACCOUNT -->
                <% else %>
                  <td class="d-flex justify-content-around align-items-center flex-md-wrap">
                  <%= link_to petsitting_path(booking.id),local:true, data: { confirm: "Etes-vous sur de vouloir annuler ce rendez-vous ?"}, :method => :delete do %>
                    <i class="fa fa-trash fa-2x ml-1" aria-hidden="true"></i>
                  <% end %>
                  </td>
                  <td><i class='small'> Utilisateur supprimé </i> </td>
                  <td><i class='small'> Utilisateur supprimé </i></td>
                  <td><i class='small'> Utilisateur supprimé </i></td>
                  <td><i class='small'> Utilisateur supprimé </i></td>
                <% end %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/petowners/index.html.erb
<h1>Petowners#index</h1>
<p>Find me in app/views/petowners/index.html.erb</p>

app/views/petowners/show.html.erb
<%= render 'layouts/flash_alert' %>
<%= render 'layouts/flash_success' %>
<div class="p-0 position-relative mt-3 mb-6">
  <div class="d-flex h-100 w-100">
    <div class="row justify-content-around w-100 ">
      <div class="col-sm-12 col-md-6">
        <ul class="nav nav-tabs tab-line">
          <li class="nav-item ml-2"> <a class="nav-link active" data-toggle="tab" href="#tab-3-1">Profil</a> </li>
          <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#tab-3-2">Mes animaux</a> </li>
          <% if current_petowner %>
          <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#tab-3-3">Mes réservations</a> </li>
          <% end %>
        </ul>
        <div class="tab-content">

          <!-- Profile Part ! -->
          <%= render 'profil' %>

          <!-- Pets Part ! -->
          <%= render 'my_pets' %>

          <!-- Reservations Part ! -->
          <%= render 'bookings' %>
        </div>
      </div>

      <!-- banner image -->
      <div class="col-md-5 d-none d-md-block p-0 avatar-div">
        <figure class="w-100 ie-height-900 position-absolute figure-petowner">
          <svg version="1.1" id="Layer_2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 881.8 917.9" style="enable-background:new 0 0 881.8 917.9;" xml:space="preserve">
            <path id="XMLID_6_" fill="url(#BgGradient)" d="M0,39.6c0,0,171-121.5,264,64.5s508.5,178.5,508.5,178.5s240-6-6,228S816,755.1,657,830.1
              s-309,106.5-445.5,76.5C75,876.6,0,717.6,0,717.6V39.6z"/>
              <path id="XMLID_5_" class="fill-dark" d="M0,291.1c0,0,133.5-100.5,169.5,91.5s103.5,204,81,283.5S0,832.6,0,832.6V291.1z"/>
              <g id="XMLID_3_">
                <defs>
                <rect id="XMLID_11_" x="175" y="18" width="650" height="850"/>
                <linearGradient id="BgGradient">
                  <stop class="fill-grad-start" offset="0%"/>
                  <stop class="fill-grad-end" offset="100%"/>
                </linearGradient>
                </defs>
                <clipPath id="XMLID_51_">
                <use xlink:href="#XMLID_11_"  style="overflow:visible;"/>
                </clipPath>
              </g>
            </svg>
        </figure>
        <span class="position-relative form-style">
          <%if @petowner.avatar.attached?%>
            <%= image_tag @petowner.avatar, alt: 'avatar' , class:'shadow-lg avatar-img '%>
          <%else%>
         <%end%>
       </span>
      </div>
    </div>
  </div>
</div>

<%= render "layouts/button_back_index"%>