config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'staticpages#index'
  get 'team', to: 'staticpages#team'
  get '404' , to: "errors#not_found"
  get '422' , to: "errors#unacceptable"
  get '500' , to: "errors#internal_error"


  resources :charges

  devise_for :petsitters,  path: 'petsitters', controllers: { sessions: "petsitters/sessions", registrations: "petsitters/registrations", passwords: "petsitters/passwords"}
  devise_for :petowners, path: 'users', controllers: { sessions: "petowners/sessions", registrations: "petowners/registrations", passwords: "petowners/passwords"}
  resources :petsitters, only: [:show, :index] do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :petowners, only: [:show], path: 'profil' do
    resources :avatars, only: [:create]
  end

  resources :pets, only: [:new, :create] do
    resources :avatars, only: [:create]
  end
  resources :organizations, only: [:show, :index, :new, :create], :path => "associations"
  resources :petsittings, only: [:new, :create, :show, :update, :destroy]
  resources :contacts, only: [:new, :create]
  resources :comments, only: [:new, :create, :index]

end

app/models/organization.rb
class Organization < ApplicationRecord
	has_many :donations

  validates :name, presence: true
  validates :describe, presence: true, length: { in: 30..2000 }
  validates :email, presence: true
  validates :date_of_birth, presence: true

  # after_create :demand_association

  def demand_association
  	AssociationMailer.demand_association(self).deliver_now
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
	  before_action :signed_in , only: [:show]

  def index
    @associations = Organization.all
  end

  def show
    @association = Organization.find(params[:id])
  end

  def signed_in
    if current_petsitter.nil? & current_petowner.nil?
      redirect_to new_petowner_session_path
    end
  end

  def new
  end

  def create
    @association = Organization.new(name: association_form_params['name'], describe: association_form_params['describe'], date_of_birth: association_form_params['date_of_birth'], email: association_form_params['email'], facebook_url: association_form_params['facebook_url'], donation_url: association_form_params['donation_url'], validate_association: false)



    if @association.save
      flash[:success] = "Votre dossier Association a bien été enregistrée !"
      redirect_to organizations_path
    else
      flash[:alert] = @association.errors.messages
      redirect_to organizations_path
    end
  end

  private

  def association_form_params
    params.require(:organization).permit(:name, :date_of_birth, :describe, :email, :facebook_url, :donation_url, :validate_association)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_banner_show.html.erb
<div class="innerpage-banner center bg-overlay-dark-7 py-7 association-banner-inner">
  <div class="container">
    <div class="row all-text-white">
      <div class="col-md-12 align-self-center">
        <h1 class="innerpage-title">Fiches associations</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item active">
              <%= link_to organizations_path do %>
                <i class="fa fa-5x fa-list "></i> Retour Associations
              <% end %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/organizations/_contactassobanner.html.erb
<div class="container">
  <div class="d-block d-md-flex bg-grad p-4 p-sm-5 border-radius-3">
    <div class="row">
      <div class="col-12 col-lg-12">
        <div class="text-center all-text-white">
          <h1>Vous représentez une association et vous souhaitez apparaitre sur notre site ?</h1>
          <h4>Remplissez le formulaire de contact et nous vous recontacterons après étude de votre dossier.</h4>
        </div>
        <div class="col-md-12 align-self-center text-center mt-4" >
          <!-- Button of modal -->
          <button type="button" class="btn btn-white" data-toggle="modal" data-target="#exampleModalCenter">
            Contactez-nous !
          </button>
          <%= render "contactassoform"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/organizations/_contactassoform.html.erb
<div class="modal fade text-left" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenter" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Entrer les informations concernant votre animal.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with model: Organization.new, local: true do |form| %>
          <div class="form-group">
            <label>Nom de l'association :</label>
            <%= form.text_field :name, class: "form-control"%>
          </div>
          <div class="form-group">
            <label>Date de création :</label>
            <%= form.date_field :date_of_birth, class: "form-control"%>
          </div>
          <div class="form-group">
            <label>Contact mail :</label>
            <%= form.email_field :email, class: "form-control"%>
          </div>
          <div class="form-group">
            <label>Page facebook :</label>
            <%= form.url_field :facebook_url, class: "form-control"%>
          </div>
          <div class="form-group">
            <label>Page de don ? </label>
            <%= form.url_field :donation_url, class: "form-control"%>
          </div>
          <div class="form-group">
            <label> Description de l'association :</label>
            <%= form.text_area :describe, class: "form-control", placeholder: "Ecrivez votre description (max 250 mots)"%>
          </div>
          <div class="modal-footer">
            <p><button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button></p>
            <p><%= form.submit "Envoyer", class: "btn btn-primary" %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/organizations/_flash_alert.html.erb
<div class="container" >
  <% if flash[:success] %>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <strong>Félicitations !</strong><h4><%= flash[:success] %></h4>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <% if flash[:warning] %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Erreur !</strong><h4><%= flash[:warning] %></h4>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/organizations/index.html.erb
<body>

  <!-- =======================
  	Banner innerpage -->
  	<div class="banner left bg-overlay-dark-5 py-7 parallax-bg association-banner-index">
  		<div class="container py-7">
  			<div class="row all-text-white pb-7">
  				<div class="col-12 col-lg-12">
  					<h1 class="title">Les associations d'aide aux animaux sur Montpellier</h1>
  					<h4>Pour trouver des informations utiles concernant vos animaux de compagnies <br> ou trouver un nouveau compagnon à 4 pattes à adopter !</h4>
  				</div>
  			</div>
  		</div>
  		<svg width="100%" height="100%" version="1.1" xmlns="http://www.w3.org/2000/svg" class="wave"><defs></defs><path id="wave-one" d=""/></svg>
  		<svg width="100%" height="100%" version="1.1" xmlns="http://www.w3.org/2000/svg" class="wave"><defs></defs><path id="wave-two" d=""/></svg>
  	</div>
  	<!-- =======================
  	Banner innerpage -->

  <!-- =======================
  Portfolio -->
      <%= render 'layouts/flash_alert' %>
<%= render 'layouts/flash_success' %>
  <div class="portfolio pb-0 mb-6">
    <div class="container">
      <div class="row">
        <div class="col-md-12 p-0">
          <div class="col-12 col-lg-12">
            <div class="title pb-4 text-left">
              <h2>Ces associations ont souhaité être référencé sur notre site.</h2>
              <h4> Vous pouvez les contacter pour avoir des informations, adopter un animal ou vous pouvez aussi les aider en participant aux collectes de dons. </h4>
            </div>
          </div>
          <div class="portfolio-wrap grid items-4 items-padding">
            <% @associations.where(validate_association: true).each do |asso| %>
              <!-- associations-card -->
              <div class="portfolio-card isotope-item">
                <%= link_to organization_path(asso) do %>
                  <div class="portfolio-card-body">
                    <div class="portfolio-card-header">
                      <%= image_tag asso.image_tag, class: 'rounded'%>
                    </div>
                    <div class="portfolio-card-footer text-center">
                      <h5 class="text-muted"> <%= asso.name%> </h5>
                    </div>
                  </div>
                <%end%>
              </div>
            <% end %>
          </div>
          <!-- portfolio wrap -->
        </div>
      </div>
    </div>
  </div>
  <!-- =======================
  Portfolio -->

<!-- =======================
  Banner contact asso -->
  <section class="blog bg-light">
  	 <%= render "contactassobanner"%>

      <!-- =======================
      Btn back index -->
      <div class="d-flex justify-content-center mt-6 mb-4">
        <%= link_to root_path do %>
        <div class="btn btn-button btn-dark">
          <i class="fa fa-angle-double-left"></i> Retour Accueil
        </div>
        <% end %>
      </div>
      <!-- Btn back index
      ======================= -->
  </section>
<!--   Banner contact asso
======================= -->
</body>

app/views/organizations/show.html.erb
<body>
<%= render "organizations/banner_show"%>


  <section class="position-relative bg-light">
    <%= render 'layouts/flash_alert' %>
<%= render 'layouts/flash_success' %>
    <div class="container ">
      <div class="row" >
        <div class="col-2 col-md-4" >
          <%= image_tag @association.image_tag, class: 'rounded shadow' %>
        </div>
        <div class="col-8 col-md-8 left pt-7 mb-4">
          <div class="row all-text-white">
            <div class="col-md-12 align-self-center">
              <p class="text-primary display-8 mb-0">Association</p>
              <p class="text-dark display-4"><%= @association.name %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="divider mt-6 mb-4"><i class="ti-heart"></i> </div>
        <div class="row">
          <div class="col-sm-12 col-lg-12 align-self-center">
				    <div class="text-center pb-4 p-lg-0 ">
              <h2><%= @association.describe_short %></h2>
				    </div>
          </div>
        </div>
      </div>
    <figure class="position-absolute bottom-0 left-0 w-100 d-none d-md-block ie-d-none mb-n3">
		  <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1920 43.4" style="enable-background:new 0 0 1920 43.4;" xml:space="preserve">
			<path id="XMLID_4_" class="fill-white" d="M0,23.3c0,0,405.1-43.5,697.6,0c316.5,1.5,108.9-2.6,480.4-14.1c0,0,139-12.2,458.7,14.3 c0,0,67.8,19.2,283.3-22.7v35.1H0V23.3z"/>
		  </svg>
	  </figure>
  </section>

  <section>
    <div class="container">
      <div class="row mb-4">
        <div class="col-md-12">
          <h2>Notre association a été créée en
            <span class="text-primary">
              <%= @association.date_of_birth %>
            </span>
          </h2>
          <h4 class="lead"> <%= @association.describe %></h4>
        </div>
      </div>
		<div class="divider"><i class="ti-heart"></i></div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row justify-content-between align-items-center">
        <!-- left side -->
      <div class="col-md-6">
        <div class="row mt-4 mt-md-0">
          <div class="col-5 offset-1 px-2 mb-3 align-self-end">
            <div data-wow-duration="0.8s" data-wow-delay="0.4s">
              <%= image_tag "associations/cat1.jpeg", class: 'border-radius-3 wow fadeInUp association-img'  %>
            </div>
          </div>
        <div class="col-6 px-2 mb-3">
          <div class="border-radius-3 wow fadeInLeft bg-grad p-2 p-sm-3 p-lg-4 p-xl-5 all-text-white" data-wow-duration="0.8s" data-wow-delay="0s">
            <h4 class="font-weight-bold">
              <%= @association.actions %>
            </h4>
          </div>
        </div>
        <div class="col-7 px-2 mb-3">
          <div class="border-radius-3 wow fadeInLeft bg-grad p-2 p-sm-3 p-lg-4 p-xl-5 all-text-white" data-wow-duration="0.8s" data-wow-delay="0s">
            <h3 class="font-weight-bold">
              <%= @association.actions_2 %>
            </h3>
          </div>
        </div>
        <div class="col-5 align-self-start pl-2 mb-3">
          <div data-wow-duration="0.8s" data-wow-delay="0.4s">
            <%= image_tag "associations/cat2.jpeg", class: 'border-radius-3 wow fadeInUp association-img' %>
          </div>
        </div>
      </div>
    </div>
        <!-- right side -->
    <div class="col-md-6 pl-lg-5">
      <blockquote class="blockquote primary-line">
        <h3 class="mb-2 "> "On n'a pas deux coeurs, l'un pour l'homme, l'autre pour l'animal. On a un coeur ou on n'en a pas."</h3>
          <cite>– Alphonse De Lamartine</cite>
      </blockquote>
        <div class="d-flex float-right m-4">
          <h2>Vous voulez <span class="text-primary"> participer</span> à notre action ? </h2>
        </div>
  <%= form_tag charges_path do %>
  <div id="error_explanation">
    <% if flash[:error].present? %>
      <p><%= flash[:error] %></p>
    <% end %>
  </div>
  <article>
    <%= label_tag(:amount, 'Montant de votre donation:') %>
    <%= number_field_tag(:amount, "", class: 'form-control', placeholder: "Indiquer le montant") %>
  </article>
  <article>
    <%= hidden_field_tag(:stripeToken) %>
    <%= hidden_field_tag(:association, params[:id]) %>
    <% if current_petowner %>
    <%= hidden_field_tag(:id_petowner, current_petowner.id) %>
    <% else current_petsitter %>
    <%= hidden_field_tag(:id_petsitter, current_petsitter.id) %>
    <%end%>
  </article>
  <button id='donateButton' class="btn btn-lg btn-grad">Donate</button>
<% end %>

    <script src="https://checkout.stripe.com/checkout.js"></script>

<script>
var handler = StripeCheckout.configure({
  key: '<%= Rails.configuration.stripe[:publishable_key] %>',
  locale: 'auto',
  name: 'Donation pour :',
  description: '<%= @association.name %>',
  token: function(token) {
    $('input#stripeToken').val(token.id);
    $('form').submit();
  }
});

      $('#donateButton').on('click', function(e) {
  e.preventDefault();

  $('#error_explanation').html('');

  var amount = $('input#amount').val();
  amount = amount.replace(/\$/g, '').replace(/\,/g, '')

  amount = parseFloat(amount);

  if (isNaN(amount)) {
    $('#error_explanation').html('<p>Please enter a valid amount in USD ($).</p>');
  }
  else if (amount < 5.00) {
    $('#error_explanation').html('<p>Donation amount must be at least $5.</p>');
  }
  else if (amount > 999999.00) {
    $('#error_explanation').html('<p>Donation amount must be at most $1M.</p>');
  }
  else {
    amount = amount * 100; // Needs to be an integer!
    handler.open({
      amount: Math.round(amount)
    })
  }
});
    </script>
  </div>
</section>

<div class="mb-6">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="divider mb-4">
                </div>
                <div class="row">
                    <div class="tags col-12 col-sm-8 text-center text-sm-left">
                        <h3 class="text-muted">Nous contacter </h3>
                    </div>
                        <div class="col-12 col-sm-4 text-center text-sm-right">
                            <ul class="social-icons si-colored-bg light">
                                <%= link_to  @association.facebook_url do %>
                                    <li class="social-icons-item social-facebook mb-0">
                                        <span class="social-icons-link"><i class="fa fa-facebook-f fa-lg"></i>
                                        </span>
                                    </li>
                                <%end%>
                                <%= mail_to @association.email do %>
                                    <li class="social-icons-item social-youtube mb-0">
                                        <span class="social-icons-link"><i class="fa fa-at fa-lg"></i>
                                        </span>
                                    </li>
                                <%end%>
                            </ul>
                        </div>
                    </div>
                    <div class="divider mt-4">
                    </div>
                </div>
            </div>
        </div>
    </div>
<div class="mb-6">
  <%= render "layouts/button_back_index"%>
</div>

</body>